<a href="https://colab.research.google.com/github/Pakhi27/LSTM-MODEL-RNN/blob/main/LSTM_MODEL_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import tensorflow as tf
# import tf.keras.layers.RNN
# import tensorflow.contrib.rnn
# sess = tf.Session()

In [7]:
!pip install tensorflow==2.9.0

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.7/511.7 MB 2.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 65.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 4.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 60.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 438.7/438.7 kB 33.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 43.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 61.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 781.3/781.3 kB 40.6 MB/s eta 0:00:00
  Attempting uninstall: keras
    Found existing installation: keras 2.15.0
    Uninstalling keras-2.15.0:
      Successfully uninstalled keras-2.15.0
  Attempting uninstall: flatbuffers
    Found existing installation: flatbuffers 24.3.25
    Uninstalling flatbuffers-24.3.25:
      Successfully uninstalled flatbuffers-24.3.25
  Attempting uninstall: ten

In [3]:
import tensorflow as tf
from tensorflow.keras.layers import LSTMCell


In [5]:
# We want to create a network that has only one LSTM cell. We have to pass 2 elements to LSTM, the prv_output and prv_state, so called, h and c. Therefore, we initialize a state vector, state. Here, state is a tuple with 2 elements, each one is of size [1 x 4], one for passing prv_output to next time step, and another for passing the prv_state to next time stamp.
LSTM_CELL_SIZE = 4  # output size (dimension), which is same as hidden size in the cell

lstm_cell = LSTMCell(units=LSTM_CELL_SIZE)
state = (tf.zeros([1,LSTM_CELL_SIZE]),)*2
state

(<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[0., 0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[0., 0., 0., 0.]], dtype=float32)>)

In [7]:
# Let define a sample input. In this example, batch_size = 1, and seq_len = 6:
sample_input = tf.constant([[3,2,2,2,2,2]],dtype=tf.float32)
print(sample_input)

tf.Tensor([[3. 2. 2. 2. 2. 2.]], shape=(1, 6), dtype=float32)


In [14]:
# This is only needed if you want to integrate the LSTM cell into a larger network

# with tf.variable_scope("LSTM_sample1"):  # Define the variable scope
output, state_new = lstm_cell(sample_input, state)
# As we can see, the states has 2 parts, the new state c, and also the output h
print ((state_new))

[<tf.Tensor: shape=(1, 4), dtype=float32, numpy=
array([[ 0.02977764, -0.06437231, -0.36232677, -0.09108386]],
      dtype=float32)>, <tf.Tensor: shape=(1, 4), dtype=float32, numpy=
array([[ 0.04390926, -0.10060275, -0.60025436, -0.09962887]],
      dtype=float32)>]


In [12]:
print(output)

tf.Tensor([[ 0.02977764 -0.06437231 -0.36232677 -0.09108386]], shape=(1, 4), dtype=float32)


In [ ]:
# Stacked LSTM

In [13]:
input_dim = 6

In [15]:
cells = []

In [ ]:
# Creating the first layer LTSM cell.

In [17]:
LSTM_CELL_SIZE_1 = 4  # Number of hidden nodes

cell1 = LSTMCell(units=LSTM_CELL_SIZE_1)
cells.append(cell1)


In [ ]:
# Creating the second layer LTSM cell.

In [28]:
LSTM_CELL_SIZE_2 = 4
cell2 =LSTMCell(LSTM_CELL_SIZE_2)
cells.append(cell2)

In [21]:
from tensorflow.keras.layers import LSTM


In [29]:
# To create a multi-layer LTSM we use the tf.contrib.rnnMultiRNNCell function, it takes in multiple single layer LTSM cells to create a multilayer stacked LTSM model.
# stacked_lstm = LSTM(cells)
stacked_lstm = LSTM(units=LSTM_CELL_SIZE_1, return_sequences=True, recurrent_initializer='glorot_uniform')  # Adjust units and return_sequences as needed


In [33]:
# Batch size x time steps x features.
batch_size = 2  # Example batch size
seq_len = 3
sample_input = tf.random.normal((batch_size, seq_len, input_dim))
output, state = stacked_lstm(sample_input)


In [ ]:
sample_input[0]  # First sequence
  [              # First time step
    [1, 2, 3, 4, 3, 2],  # Features for that time step
    [1, 2, 1, 1, 1, 2],  # Features for the second time step
    [1, 2, 2, 2, 2, 2]   # Features for the third time step
  ]
sample_input[1]  # Second sequence (following the same structure)

In [36]:
#Batch size x time steps x features.
# Lets say the input sequence length is 3, and the dimensionality of the inputs is 6. The input should be a Tensor of shape: [batch_size, max_time, dimension], in our case it would be (2, 3, 6)
sample_input = [[[1,2,3,4,3,2], [1,2,1,1,1,2],[1,2,2,2,2,2]],[[1,2,3,4,3,2],[3,2,2,1,1,2],[0,0,0,0,3,2]]]
sample_input

[[[1, 2, 3, 4, 3, 2], [1, 2, 1, 1, 1, 2], [1, 2, 2, 2, 2, 2]],
 [[1, 2, 3, 4, 3, 2], [3, 2, 2, 1, 1, 2], [0, 0, 0, 0, 3, 2]]]

In [39]:
sample_input = [[[1, 2, 3, 4, 3, 2], [1, 2, 1, 1, 1, 2], [1, 2, 2, 2, 2, 2]],
                [[1, 2, 3, 4, 3, 2], [3, 2, 2, 1, 1, 2], [0, 0, 0, 0, 3, 2]]]
sample_input = tf.constant(sample_input, dtype=tf.float32)  # Convert to a constant tensor

# Create Multi-Layer LSTM using Keras LSTM layer
stacked_lstm = LSTM(units=LSTM_CELL_SIZE, return_sequences=True, recurrent_initializer='glorot_uniform')

# No need for placeholder in eager execution
output, state = stacked_lstm(sample_input)

# Print the output
print(output)
output_array = output.numpy()
print(output_array)
# (2,3,4)

tf.Tensor(
[[-0.07977189  0.18436068  0.02193443 -0.06541126]
 [-0.4088226   0.3956812   0.15312442  0.05524919]
 [-0.27391064  0.39224628  0.126778    0.0244112 ]], shape=(3, 4), dtype=float32)
[[-0.07977189  0.18436068  0.02193443 -0.06541126]
 [-0.4088226   0.3956812   0.15312442  0.05524919]
 [-0.27391064  0.39224628  0.126778    0.0244112 ]]
